megfile/s3.py, tests/test_s3.py
Optimize the speed under such circumstance: only last part of path contains non-recursive wildcard characters.
And now only bucket with wildcard characters will be matched with all bucket names, which will help speedup slightly.
=> Further speedup s3 glob

.github/workflows/on-push.yaml
So we can keep an eye on the code coverage. See also: https://docs.codecov.com/docs/quick-start
=> upload coverage to Codecov

megfile/errors.py, megfile/http.py, megfile/http_path.py, tests/test_http.py
https://github.com/megvii-research/megfile/issues/94
=> Http getsize and getmtime

megfile/s3_path.py
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-endpoints.html#endpoints-precedence
按照 awscli / asyncbotocore 这两个库的约定，额外从环境变量 `AWS_ENDPOINT_URL` 和 配置文件 `endpoint_url`（之前是 `s3.endpoint_url`）读取 endpoint_url
读取的顺序保持不变，优先读取之前的环境变量和配置，以保持向前兼容
=> feat: read endpoint_url from more config keys & env vars

megfile/lib/base_prefetch_reader.py, megfile/lib/combine_reader.py, megfile/lib/s3_buffered_writer.py, megfile/lib/s3_limited_seekable_writer.py, megfile/lib/shadow_handler.py
这里：https://github.com/numpy/numpy/issues/7126
不幸遇到，如果一个东西是uint64，一个东西是int64，block_offset就变np.float64，因为uint64没法向上变int，只能变到float，然后大家向上对齐就变float了。然后在后面for loop的时候无情报错。保险起见，建议改掉= =
=> makesure block_offset is int

megfile/errors.py, megfile/s3_path.py
发现火山云这边访问太频繁会报 429，这个在 s3 的定义上是有的  
火山云建议是碰到了之后 backoff 重试
=> feat: retry 429 errors

megfile/errors.py
又发现了一些新的错误，catch 一下
其中，RequestTimeout 是 s3 的 [标准定义](https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html)，Timeout 是火山定义的
=> feat: retry timeout errors

megfile/cli.py, megfile/pathlike.py, megfile/smart_path.py, megfile/utils/__init__.py, tests/test_smart.py, tests/test_smart_path.py, tests/utils/test_init.py
Before
```bash
$ megfile ls tos://bucket/
INFO:megfile.s3_path:using ~/.aws/config: https://tos-s3-cn-beijing.ivolces.com
../../s3:/bucket/1
../../s3:/bucket/2
```
After
```bash
$ megfile ls tos://bucket/
INFO:megfile.s3_path:using ~/.aws/config: https://tos-s3-cn-beijing.ivolces.com
1
2
```
感觉这个实现也比较苟，但科学实现改的太大有点费劲，简单讨论下
1. 现在实现只是更新了下 smart_relpath 的定义：
1. 之前 URIPath.relpath 会抛异常，现在改成对于相同 prefix 的路径可以返回一个字符串，其他情况抛异常
2. SmartPath.relpath 适配了一下 alias 的路径转换
3. megfile ls 这块用 smart_relpath 代替之前的 os.path.relpath 获取相对路径
2. 这样改之后，alias 的定义会变成：
1. smart 相关函数返回的路径和之前一样，都是 unaliased，去除 alias 的原路径
2. smart 相关函数如果输入超过一个路径，可以处理第二个路径的 alias，例如 smart_relpath / smart_copy 等
3. 期待的科学行为的定义是（不会在这个 MR 中实现）：
1. smart 相关函数返回的路径和之前一样，都是 aliased，即不要去除 alias 的路径
2. 但这个定义涉及修改的接口非常多，需要有个方案设计
TODO
1. 补一下单元测试
=> fix: fix megfile ls for alias paths

megfile/config.py, megfile/lib/s3_prefetch_reader.py, megfile/s3_path.py, megfile/utils/__init__.py, tests/test_s3.py, tests/utils/test_init.py
用起来发现有几个细节上的 bug
1. 阿里云 oss 对于不到一个 block(8M) 的文件，请求返回的 headers 里没有带 Content-Range，而是 Content-Length，所以对 S3PrefetchReader 做了一些修改
1. 这些修改是向前兼容的，因为之前 headers 里不包含 Content-Range 时会抛 KeyError，代码并没有捕获会直接报错，因此认为之前没出现过这种情况
2. 在跳转时把 headers 里的一些鉴权相关的字段删了
1. 跳转其他域名的时候带着源域名的鉴权信息被认为是不安全的，抄了下 go 的实现，在跳转域名发生变化时不带 auth 相关的 headers 了
2. 为了实现这个功能，patch 了一个更靠下的函数
=> fix: redirect fix auth headers issue

megfile/config.py, megfile/lib/s3_buffered_writer.py, megfile/s3_path.py, tests/lib/test_s3_buffered_writer.py
megfile 写入大文件时会吃到
```
megfile.errors.S3UnknownError: Unknown error encountered: 's3://...', error: botocore.exceptions.ClientError('An err
or occurred (InvalidArgument) when calling the UploadPart operation: Part number must be an integer between
1 and 10000, inclusive.'), endpoint: 'https://oss-cn-beijing-internal.aliyuncs.com'
```
报错，而 fsspec 默认 block size = 50MB 则几乎不会遇到这个问题
为了保证 megfile 写入小文件时依然可以使用较大并发产生速度优势，并可以写入大文件，设计了一种阶梯上升的 block size，在写入 10 / 100 / 1000 / 10000 块时 block size 翻倍，这样在 10000 part number 限制下最大能上传 600GB 左右的文件
=> feat: s3 buffered writer block size autoscale

megfile/lib/s3_prefetch_reader.py
When etag is not returned by s3 server, megfile crashes with `[KeyError] 'ETag's]`. We should be able to handle those cases.
=> Fix `KeyError` crash when etag is not returned

megfile/errors.py, megfile/fs.py, megfile/fs_path.py, megfile/hdfs.py, megfile/hdfs_path.py, megfile/pathlike.py, megfile/s3.py, megfile/s3_path.py, megfile/sftp.py, megfile/sftp_path.py, megfile/smart.py, megfile/stdio.py, megfile/stdio_path.py, tests/test_hdfs.py, tests/test_s3.py, tests/test_sftp.py, tests/test_sftp_path.py
- Remove the `followlinks` parameter from `hdfs_listdir`, `hdfs_load_from`, `hdfs_scandir`, `HdfsPath.load`, `HdfsPath.scandir`, and keep the behavior as `followlinks=False`.
- Remove the `followlinks` parameter from `s3_access`, `s3_listdir`, `s3_load_from`, `s3_scandir`, `s3_glob`, `s3_glob_stat`, `s3_iglob`, `s3_load_content`, `S3Path.access`, `S3Path.listdir`, `S3Path.load`, `S3Path.scandir`, `S3Path.glob`, `S3Path.glob_stat`, `S3Path.iglob`, `S3Path.iterdir`, and keep the behavior as `followlinks=False`.
- Remove the `missing_ok` parameter from `s3_listdir`, `s3_scandir`, `S3Path.listdir`, `S3Path.scandir`, and set the default behavior to `missing_ok=False`.
- `Path.iterdir` and `Path.scandir` no longer guarantees dictionary order. If order is required, use `Path.listdir`.
- Fix the …
=> refactor:remove missing_ok and follow_links in listdir and iterdir

megfile/errors.py
```
megfile.errors.S3UnknownError: Unknown error encountered: 's3://bucket/key', error: botocore.exceptions.SSLError('SSL validation failed for https://bucket.oss-cn-beijing-internal.aliyuncs.com/key?uploadId=23D0F106649149C9A1320899D6A77C63&partNumber=11 [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)'), endpoint: 'https://oss-cn-beijing-internal.aliyuncs.com'
megfile.errors.S3UnknownError: Unknown error encountered: 's3://bucket/key', error: botocore.exceptions.SSLError('SSL validation failed for https://bucket.oss-cn-beijing-internal.aliyuncs.com/key?uploadId=789CA71B70B44AFE97043AD927215D04&partNumber=11 EOF occurred in violation of protocol (_ssl.c:2426)'), endpoint: 'https://oss-cn-beijing-internal.aliyuncs.com'
```
最近老吃到这种错，拦一手，看起来是在 ssl …
=> fix: retry unexpected eof while reading

megfile/cli.py
让 megfile sync 和 megfile cp 一样，默认使用 num_cpus * 2 个线程
=> feat: update megfile sync default worker number

.github/workflows/run-tests.yml, megfile/smart_path.py
https://github.com/megvii-research/megfile/issues/497
=> fix:fix smart_move bug when path with protocol alias

megfile/cli.py, megfile/smart.py, tests/test_cli.py
1. 每个文件拷贝完打印一下完成，可以通过 --verbose 开启
2. 扫描文件改为在线程里完成，这样可以边扫边拷，对大量小文件比较友好
=> refactor: megfile sync

megfile/s3_path.py, tests/test_s3.py
boto3 在升级到 1.36 之后，部分默认配置改变导致在 tos / oss / obs(huawei) 上，upload object / upload part 会报错
相关 issue 包括
* https://github.com/boto/boto3/issues/4400
* https://github.com/boto/boto3/issues/4409
1. `An error occurred (InvalidArgument) when calling the PutObject operation: aws-chunked encoding is not supported with the specified x-amz-content-sha256 value.`
2. `An error occurred (ContentSHA256Mismatch) when calling the PutObject operation: The provided content-sha256 does not match what was computed.`
`1.36` 是大约 1 月份发版的，不过截止目前 boto3 已经升级到 `1.37` 也没计划修复这个问题，并且从维护者态度看估计未来也不会处理
https://github.com/boto/boto3/issues/4409#issuecomment-2620016816
因此在 megfile 里改了下默认配置已获得最大程度的兼容
=> fix tos / oss upload issue for boto3 >= 1.36

megfile/lib/s3_prefetch_reader.py
oss 产生的 presign url 上，end 如果超过文件长度会返回整个文件，导致读错内容，这里修一下
过程是服务端自己实现了个 s3 接口做了鉴权，鉴权后 302 跳转到了一个 presign url 上，读取 presign url 时碰到了这个问题
=> hotfix oss presign url fetch data

megfile/errors.py, megfile/http_path.py, megfile/lib/http_prefetch_reader.py, tests/lib/test_http_prefetch_reader.py
在用 megfile 下载 http 协议的数据，有多线程 prefetch 确实快，且还能直接输出到 s3 不用落盘
不过使用过程中发现
1. http 目前实现没有复用 session，按 requests 建议复用会比较好 https://requests.readthedocs.io/en/latest/user/advanced/
> So if you’re making several requests to the same host, the underlying TCP connection will be reused, which can result in a significant performance increase
2. 有些 http 请求需要一些特殊的 auth header，因此抽出来个 DEFAULT_REQUEST_KWARGS 方便注入 headers
因为很多时候用的是 smart_copy 之类的函数，实在离得太远，感觉靠传参得改太多接口，所以打算先这么凑合用用     
3. 顺便给 errors.patch_method 加了个 verbose 参数，方便控制是否打印 log，这函数我会在别的库也用，有时候错误多打印太多影响阅读
=> better http impl

megfile/cli.py, megfile/s3_path.py
目前 megfile 对以 / 结尾的文件定义不一致
1. scan / glob / walk 之类的 list 文件的函数，把 / 结尾的文件当成一个文件名为空的文件
2. 其他对文件操作的函数，把 / 结尾的文件当成目录
这导致当目录中有 / 结尾的文件时，scan 会扫描出这种文件，但进一步 copy / open 时会报错
因此这个 PR 中修改了这部分的定义
1. 对于 scan / glob / walk 之类的 list 文件的函数，不再返回 / 结尾的文件
2. 有个特例是在 remove 中依然可以扫描到这种文件，以确保这种文件还能被正常删除
=> fix empty s3 file name issue
