megvii-research/megfile

- megfile/s3.py
- tests/test_s3.py
> s3_open support ab / rb+

- megfile/lib/glob.py
- megfile/s3.py
- tests/test_s3.py
https://github.com/megvii-research/megfile/issues/8
> optimize glob

- megfile/errors.py
https://github.com/megvii-research/megfile/issues/44
> add should retry errors

- .github/workflows/on-push.yaml
- .pyre_configuration
- LICENSE.pyre
- scripts/convert_results_to_sarif.py
Pyre is a type checker, more faster than PyType. It also includes a security scanner, Pysa, which is not yet enabled. Maybe we could set it up later.
> Introduce pyre

- megfile/cli.py
- megfile/smart.py
- megfile/smart_path.py
https://github.com/megvii-research/megfile/issues/89
> 修复cli cp 和 mv 行为

- megfile/http.py
- megfile/smart.py
- megfile/smart_path.py
- tests/test_http.py
- tests/test_smart.py
https://github.com/megvii-research/megfile/issues/88
> 添加 smart_copy src_path 为 http 情况的测试代码

- megfile/fs_path.py
- megfile/pathlike.py
- megfile/smart_path.py
https://github.com/megvii-research/megfile/issues/100
> update smart_open for pipe

- megfile/fs.py
- megfile/fs_path.py
- megfile/smart.py
- megfile/smart_path.py
- tests/test_fs.py
- tests/test_fs_path.py
- tests/test_smart.py
- tests/test_smart_path.py
Add CRUD methods of symlink
#issue #13
> Add symlink crud

- megfile/fs.py
- megfile/fs_path.py
- megfile/smart.py
- megfile/smart_path.py
- tests/test_fs.py
- tests/test_fs_path.py
- tests/test_smart.py
- tests/test_smart_path.py
add all relevant funtions of symlink
issue#13
> Add symlink relevant functions

- .github/workflows/run-tests.yml
- megfile/pathlike.py
- requirements-dev.txt
- setup.py
- tests/lib/test_s3_buffered_writer.py
- tests/lib/test_s3_limited_seekable_writer.py
- tests/test_s3.py
https://github.com/megvii-research/megfile/issues/116
> Support python 3.10

- megfile/errors.py
- megfile/s3.py
- tests/test_s3.py
boto3 doc: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.delete_objects
> handle remove file errors

- megfile/errors.py
- megfile/s3.py
- tests/test_s3.py
Reverts megvii-research/megfile#132
> Revert "handle remove file errors"

- .github/workflows/run-tests.yml
- megfile/s3.py
- setup.py
- tests/test_s3.py
- tests/test_smart.py
> update relevant functions

- megfile/smart.py
- tests/test_smart.py
https://github.com/megvii-research/megfile/issues/140
> Add smart_getmd5_by_paths

- megfile/http_path.py
https://github.com/megvii-research/megfile/issues/145
> fix http open bug

- megfile/version.py
https://github.com/megvii-research/megfile/issues/145
> bump version

- megfile/smart.py
- tests/test_smart.py
https://github.com/megvii-research/megfile/issues/148
> fix smart_getmd5_by_paths

- megfile/utils/__init__.py
- tests/test_s3.py
https://github.com/megvii-research/megfile/issues/130
> fix mode with +

- requirements-dev.txt
remove py35 requirements and upgrade cryptography version
> fix(requirements): fix for security

- megfile/errors.py
- tests/test_errors.py
retry when catch botocore.exceptions.ResponseStreamingError
> perf(errors): add retry error

- megfile/fs.py
- megfile/fs_path.py
- megfile/pathlike.py
- megfile/s3.py
- megfile/s3_path.py
- megfile/smart_path.py
- scripts/generate_file.py
- tests/test_smart.py
- tests/test_smart_path.py
- tests/test_smart_purepath.py
主要是将 Path 类中的 mkdir 和 pathlib 对其，加了两个参数，并保持函数接口不变
> feat: mkdir 和 pathlib 对其

- megfile/pathlike.py
- megfile/s3.py
- megfile/s3_path.py
https://github.com/megvii-research/megfile/issues/13
> feat: s3 is_dir and walk support followlink

- megfile/__init__.py
- megfile/fs.py
- megfile/fs_path.py
- megfile/s3.py
- megfile/smart.py
- scripts/generate_file.py
- tests/test_fs.py
- tests/test_s3.py
- tests/test_smart.py
https://github.com/megvii-research/megfile/issues/182
> feat(smart):add smart_lstat

- megfile/smart.py
- tests/test_smart.py
https://github.com/megvii-research/megfile/issues/184
> fix:fix smart_sync error when file name in dir is empty str

- megfile/fs_path.py
- megfile/interfaces.py
- megfile/s3_path.py
- megfile/sftp_path.py
- tests/test_fs.py
- tests/test_s3.py
https://github.com/megvii-research/megfile/issues/181
> feat:smart_scandir support ‘with’ operate

- megfile/pathlike.py
- tests/test_http.py
- tests/test_smart_path.py
https://github.com/megvii-research/megfile/issues/183
> fix:fix stat properties default value

- README.md
- megfile/s3_path.py
- megfile/smart.py
- megfile/smart_path.py
- scripts/generate_file.py
- tests/test_s3.py
- tests/test_smart.py
https://github.com/megvii-research/megfile/issues/155
> feat(s3): support custom profile name

- megfile/http_path.py
- megfile/s3_path.py
- megfile/sftp_path.py
- tests/test_http.py
- tests/test_s3.py
- tests/test_sftp.py
- tests/test_sftp_path.py
- perf http open
- fix `SftpPath.parts`
- fix s3 client when profile_name not exist
> ci:add ci and fix bugs

- megfile/cli.py
- megfile/fs.py
- megfile/fs_path.py
- megfile/hdfs.py
- megfile/hdfs_path.py
- megfile/http_path.py
- megfile/pathlike.py
- megfile/s3.py
- megfile/s3_path.py
- megfile/sftp.py
- megfile/sftp_path.py
- megfile/smart.py
- tests/test_fs.py
- tests/test_hdfs.py
- tests/test_s3.py
- tests/test_sftp.py
- tests/test_smart.py
https://github.com/megvii-research/megfile/issues/92
> feat: support overwrite in copy, sync and move

- README.md
- docs/configuration/s3.md
- megfile/cli.py
- megfile/s3_path.py
- tests/test_s3.py
支持设置 s3 [短期凭证](https://docs.aws.amazon.com/zh_cn/cli/latest/userguide/cli-authentication-short-term.html)
aliyun oss 支持这个功能，适配一下
> feat: support AWS_SESSION_TOKEN

- megfile/s3_path.py
- tests/test_s3.py
支持一些内部服务（s3 套壳）做 307 跳转
1. 功能点介绍
1. 发现 boto 并不支持跳转，因此 python 一系的 sdk 应该都不支持这个功能，但 aws-sdk-go 默认支持；加上感觉可以作为一个特色功能
2. 但完整实现 3xx 跳转比较费劲，boto 下面直接调用 urllib3，没用 requests，跳转得自己实现，比较麻烦，所以这里根据需求先只实现了 GET 请求的跳转，未来最多再加上 OPTION，POST / PUT 比较复杂可能未来也不会支持
2. 已知问题
1. 测试很难写，所以在内部服务上测了一下，不准备补这里的测试了
2. patch 的 botocore 函数比较深，可能未来会有兼容性问题，但看了下 botocore 的代码，这部分接口上已经有 10 年没动了，感觉应该还好
PS 关于 3xx 跳转找到的一些资料
* https://storychief.io/blog/301-302-307-308-redirect
> feat: support s3 proxy 307 redirect

- docs/configuration/common.md
- megfile/config.py
- tests/test_config.py
https://github.com/megvii-research/megfile/issues/434
> feat:support kubernetes canonical form quantity

- megfile/cli.py
- megfile/config.py
- megfile/s3_path.py
1. 给了一个 MEGFILE_LOG_LEVEL 配置日志级别，如果配置了默认打开日志（logging.basicConfig）
2. cli 上加了个 --log-level 参数配置日志级别，优先级是 cli 参数传入 > 环境变量
TODO: doc 上写一下这部分功能
> feat: add env MEGFILE_LOG_LEVEL

- megfile/errors.py
- megfile/s3_path.py
- requirements-dev.txt
- scripts/print_pyre_errors_by_file.py
- tests/test_errors.py
- tests/test_fs.py
https://github.com/megvii-research/megfile/issues/478
> fix:fix pickle load S3UnknownError bug

- megfile/errors.py
对 aliyun oss 的一些自定义 code 做下 retry
定义见 https://www.alibabacloud.com/help/zh/oss/support/http-status-code-503?spm=a2c63.p38356.0.i12
> add s3 retry codes for oss

- megfile/errors.py
- tests/test_errors.py
发现还有各种换着花儿的 SSLError，干脆全部 retry 了
> retry all botocore.exceptions.SSLError

- megfile/s3_path.py
- tests/test_s3.py
收到汇报说 s3_glob 返回的文件不对，查了一圈发现是 s3_glob 实现里，中间过程把 profile 去掉了，导致部分操作用了 default profile
出问题的代码在
https://github.com/megvii-research/megfile/blob/main/megfile/s3_path.py#L598
这里的 _s3_pathname 是个去除 profile 的 s3 url
这个 MR 做出的改动是，把 glob 相关的几个函数都改成输入带 profile 的 s3 url
> fix s3_glob with profile

- megfile/utils/__init__.py
干了个傻逼事儿，用网页编辑器编辑，一不小心直接推到 main 了
> hotfix get_human_size

- megfile/errors.py
想起来用 logging level 就可以控制，不用这么奇怪的招数了
> remove verbose in patch_method

- megfile/errors.py
搞不定的时候打印一下，光看异常里的报错信息不知道重试了几次
UPDATE: https://github.com/megvii-research/megfile/pull/517/files#diff-ec785e5e518e9f3a04722a9bbf8671a32ce4c703afb4e376eb6cc72e30727952L169
再加个 change，这里改错了...
> log error if cannot handle error

- megfile/smart.py
- tests/test_smart.py
https://github.com/megvii-research/megfile/issues/530
> perf:optimize smart_open for S3-to-S3 transfers using s3+protocol

- megfile/s3_path.py
#466 的后续，remove 因为使用了 exists，在 oss 多版本上碰到了删不掉文件的问题：remove 最上面的 exists 判错了，认为目录不存在就直接报错了
改成在 list 之后发现 0 个文件时再报错，少个 exists 性能也更好一些
> fix remove for oss

- megfile/smart.py
- tests/test_smart.py
实现了一些自定义协议（huggingface），但目前逻辑没法注册一个带 profile 的 s3 和自定义协议之间的 copy_func
改了一下支持这种 case
> fix _get_copy_func between s3+ and file

- megfile/lib/compare.py
- megfile/s3_path.py
- tests/utils/test_compare.py
- dst 为 s3 path 的情况下，都应该走 upload 逻辑
- src 为 s3 path 并且 dst 不是 s3 path 时，为 download
- 其他的是 copy
> fix:fix samefile logic error for s3+profile in sync
